name: Deploy GH Pages

on:
  push:
    branches: [master]
  workflow_dispatch:
  repository_dispatch:
    types: [update_diff]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11
          run_install: true
          cache: true
      - name: Setup Node.JS
        uses: actions/setup-node@v6
        with:
          node-version: latest
          cache: "pnpm"
      - name: Build vitepress
        run: pnpm docs:build
      - name: Configure pages
        uses: actions/configure-pages@v6
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: docs/.vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v4
